<a href="https://colab.research.google.com/github/polinarodionova19/p_rodionova_innopolis/blob/main/17Python_%D0%94%D0%97_%D0%A0%D0%BE%D0%B4%D0%B8%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

matrix = np.zeros((4, 5), dtype = int) #создаем матрицу 4x5 с нулевыми значениями и устанавливаем целочисленный тип
fibonacci = [0, 1] #создаем вспомогательный массив, который будем заполнять числами Фибоначчи с первыми двумя значениями ряда Фибоначчи
for i in range(4): #индекс строки
    for j in range(5): #индекс столбца
        if i == 0 and j == 0: #для первого значения (1 строка 1 столбец)
            matrix[i, j] = fibonacci[0] # устанавливаем значение 0
        elif i == 0 and j == 1: # для второго значения (1 строка 2 столбец)
            matrix[i, j] = fibonacci[1] #  устанавливаем значение 1
        else: #для всех остальных значений
            fibonacci.append(fibonacci[-1] + fibonacci[-2]) #в массив добавляем значение, равное сумме двух предыдущих значений
            matrix[i, j] = fibonacci[-1] #текущему (в цикле) значению матрицы присваиваем последнее записанное значение в вспомогательный массив
print(matrix) #выводим итоговую матрицу

#считаем сумму, минимум и максимум для каждой строки:

print(matrix.sum(axis=1))
print(matrix.min(axis=1))
print(matrix.max(axis=1))

#считаем сумму, минимум и максимум для каждого столбца
print(matrix.sum(axis=0))
print(matrix.min(axis=0))
print(matrix.max(axis=0))

matrix[matrix > 500] = 1 # замена значений больше 500 на 1
print(matrix) #выводим итоговую матрицу
#строка для проверки связи с GitHub:)

[[   0    1    1    2    3]
 [   5    8   13   21   34]
 [  55   89  144  233  377]
 [ 610  987 1597 2584 4181]]
[   7   81  898 9959]
[  0   5  55 610]
[   3   34  377 4181]
[ 670 1085 1755 2840 4595]
[0 1 1 2 3]
[ 610  987 1597 2584 4181]
[[  0   1   1   2   3]
 [  5   8  13  21  34]
 [ 55  89 144 233 377]
 [  1   1   1   1   1]]
